name: generate-pages

on:
  push:
    branches: [ "master" ]
    
jobs:
  generate-pages:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
          ref: 'gh-pages'
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'npm'
      - run: npm ci
      - name: git setting
        run: |
          git config --local user.email "${{ vars.PAGES_AUTO_GENERATOR_GIT_USER_EMAIL }}"
          git config --local user.name "${{ vars.PAGES_AUTO_GENERATOR_GIT_USER_NAME }}"
      - name: merge from origin/master
        run: git merge -X theirs origin/master
      - name: generate pages
        run: npm run generate
      - name: Commit files
        run: |
          git add ./dist
          git commit -m "auto: generate pages" -a
      - name: Push files
        run: |
          git pull
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}