name: generate-pages

on:
  workflow_run:
    workflows: 
      - merge-changes-to-gh-pages
    types:
      - completed
jobs:
  generate-pages:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
          ref: 'gh-pages'
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: git setting
        run: |
          git config --local user.email "${{ vars.PAGES_AUTO_GENERATOR_GIT_USER_EMAIL }}"
          git config --local user.name "${{ vars.PAGES_AUTO_GENERATOR_GIT_USER_NAME }}"
      - name: generate pages
        run: npm run generate
      - name: Commit files
        run: |
          if [[ 0 < $(git status -s ./.output/public | wc -l) ]]; then 
            git add ./.output/public
            git commit -m "auto: generate pages" -a
            git pull
            git push origin gh-pages
          else
            echo No files changed.
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}